# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies (ignoring scripts to avoid preinstall issues)
RUN npm install --ignore-scripts

# Copy rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose commonly used port if required (not strictly necessary for MCP over stdio)
# EXPOSE 3000

# Start the MCP server
CMD [ "npm", "run", "start" ]
